# Generated by Django 4.2.24 on 2025-09-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcaoCadastro',
            fields=[
                ('id_acao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_acao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BaralhoCadastro',
            fields=[
                ('id_carta', models.AutoField(primary_key=True, serialize=False)),
                ('nome_carta', models.CharField(max_length=100)),
                ('tipo_carta', models.CharField(max_length=50)),
                ('cor_carta', models.CharField(max_length=50)),
                ('descricao_carta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id_partida', models.AutoField(primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('id_jogador_amarelo', models.IntegerField(blank=True, null=True)),
                ('id_jogador_azul', models.IntegerField(blank=True, null=True)),
                ('id_jogador_preto', models.IntegerField(blank=True, null=True)),
                ('id_jogador_roxo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabuleiroCadastro',
            fields=[
                ('id_casa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_casa', models.CharField(max_length=100)),
                ('acao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id_jogador', models.AutoField(primary_key=True, serialize=False)),
                ('nome_jogador', models.CharField(max_length=100)),
                ('cor_jogador', models.CharField(max_length=50)),
                ('id_baralho', models.IntegerField(blank=True, null=True)),
                ('id_casa', models.IntegerField(blank=True, null=True)),
                ('id_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partida')),
            ],
        ),
        migrations.CreateModel(
            name='ControlePartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_jogar', models.IntegerField(blank=True, null=True)),
                ('proximo_jogar', models.IntegerField(blank=True, null=True)),
                ('id_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Baralho',
            fields=[
                ('id_baralho', models.AutoField(primary_key=True, serialize=False)),
                ('lista_de_cartas', models.TextField()),
                ('id_jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jogador')),
            ],
        ),
    ]
