# Generated by Django 4.1.9 on 2025-09-14 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baralho',
            name='id_partida',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.partida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baralho',
            name='id_jogador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jogador'),
        ),
        migrations.AlterField(
            model_name='baralho',
            name='lista_de_cartas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
