# Generated by Django 4.1.9 on 2025-09-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_baralho_id_partida_alter_baralho_id_jogador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlepartida',
            name='cartas_descartadas',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='controlepartida',
            name='cartas_jogadores',
            field=models.TextField(default='[]'),
        ),
    ]
